version: '2'

services:
  web:
    build:
      context: ./docker
    container_name: "web"
    ports:
      - "80:80"
    volumes:
      - .:/var/www

  mysql:
    image: mysql:5.7
    container_name: "db-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .data/mysql:/var/lib/mysql/
